package com.hakancevik.youtubemusicclone.common

object Constants {
    // Weather
    const val DEFAULT_VALUE = 0f
    const val INVISIBLE_ALPHA = 0f
    const val VISIBLE_ALPHA = 1f
    const val OVERLAP_CURRENT_INFORMATION_WIDGET_TEMPERATURE_THRESHOLD = 300f
    const val OVERLAP_CURRENT_INFORMATION_WIDGET_DESCRIPTION_THRESHOLD = 260f
    const val OVERLAP_CURRENT_INFORMATION_WIDGET_CITY_NAME_THRESHOLD = 240f
    const val SCROLLABLE_WIDGET_TOP_POINT = 220f
    const val CURRENT_INFORMATION_WIDGET_TRANSLATION_Y = 600
    const val CURRENT_INFORMATION_WIDGET_ALPHA_ANIMATION_TOP_THRESHOLD = 161
    const val CURRENT_INFORMATION_WIDGET_ALPHA_ANIMATION_DURATION = 100
    const val INFORMATION_BOX_ALPHA = 0.7F

    const val MUSIC_PLAYER = "Music Player"


}
